---
title: Математична статистика. _Лабораторна робота № 2_. Створення електронного документу
  в стилі 'грамотного програмування' засобами R
author: "Ihor Polynko, `r format(Sys.Date(), '%Y')`"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    df_print: paged
  html_notebook:
    toc: true
    toc_float: true
    highlight: tango
fontsize: 12pt
header-includes: \usepackage[T2A]{fontenc} \usepackage[utf8]{inputenc} \usepackage[russian]{babel}
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
# Завантажуємо необхідні пакети
library(ggplot2)
library(dplyr)
```

```{r}
# Параметри функції
b0 <- 2
b1 <- 3
b2 <- 1.57

# Генерація даних
x <- seq(-1, 1, 0.1)
y <- b0 + b1 * x + b2 * x^2
df <- data.frame(x = x, y = y) # Створюємо таблицю даних

# Побудова графіка з використанням %>%
df %>%
  ggplot(aes(x = x, y = y)) +
  geom_line(color = "red", linewidth = 1) +
  geom_point(color = "blue", size = 2) +
  labs(
    title = "Графік функції",
    x = "x",
    y = "y"
  )
```

```{r}
df <- data.frame(x = x, y = y) # Створюємо таблицю даних

#install.packages("rio") # істаляція пакету
library(rio)
export(df, "data/data.csv")

# packages <- c("rio", "dplyr", "tidyr", "ggplot2")

# install.packages(packages)

# lapply(packages, library, character.only=TRUE)

DT::datatable(df)
```

```{r}
dfNew <- import("data/data.csv")

# Таблиця засобами knitr
knitr::kable(head(dfNew),
             caption = "_Табл. 1. Фрагмент таблиці даних_")
```

